var X2JS = require('./libs/xml2json');

function getNodosCercanos() {
  function success(pos) {
    console.log("Position found");
    var soapBody = '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" targetNamespace="http://impl.services.infotusws.tussam.com/" xmlns:ns1="http://services.infotusws.tussam.com/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http"><soap:Body><getNodosCercanos xmlns="http://services.infotusws.tussam.com/"><latitud xmlns="">'+pos.coords.latitude+'</latitud><longitud xmlns="">'+pos.coords.longitude+'</longitud><radio xmlns="">1000</radio></getNodosCercanos></soap:Body></soap:Envelope>';

    var method = 'POST';
    var url = 'http://www.infobustussam.com:9005/InfoTusWS/services/InfoTus?WSDL';

    // Create the request
    var req = new XMLHttpRequest();
    req.open(method, url,true);
    req.setRequestHeader("Authorization", "Basic aW5mb3R1cy11c2VybW9iaWxlOjJpbmZvdHVzMHVzZXIxbW9iaWxlMg==");
	  req.setRequestHeader("Content-Type", "text/xml; charset=utf-8");
    req.setRequestHeader("SOAPAction", "");
    req.setRequestHeader("deviceid", Pebble.getAccountToken());

    // Send the request
    req.send(soapBody);

    // Specify the callback for when the request is completed
    req.onload = function() {
      // The request was successfully completed!
      console.log('Got response: ' + this.responseText);
      console.log("################");
      var x2js = new X2JS();
      var xmlText = this.responseText;
      var jsonObj = x2js.xml_str2json( xmlText );
      console.log(JSON.stringify(jsonObj));
    };

    /* JSONOBJECT EXAMPLE FROM XML RESPONSE
    {
   "Envelope":{
      "Body":{
         "getNodosCercanosResponse":{
            "nodosCercanos":{
               "nodo":[
                  {
                     "codigo":"235",
                     "descripcion":"Feria (Cruz Verde)",
                     "proximidad":"111.12999725341797",
                     "posicion":{
                        "latitud":"37.39825439453125",
                        "longitud":"-5.991580009460449",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"14",
                              "label":"14",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"121",
                              "label":"C5",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"285",
                     "descripcion":"San Luis (Inocentes)",
                     "proximidad":"189.22000122070312",
                     "posicion":{
                        "latitud":"37.39845275878906",
                        "longitud":"-5.988192558288574",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"236",
                     "descripcion":"Feria (Relator)",
                     "proximidad":"233.27000427246094",
                     "posicion":{
                        "latitud":"37.40003204345703",
                        "longitud":"-5.991754531860352",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"14",
                              "label":"14",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"121",
                              "label":"C5",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"798",
                     "descripcion":"San Luis (Pza. San Marcos)",
                     "proximidad":"291.6499938964844",
                     "posicion":{
                        "latitud":"37.39645767211914",
                        "longitud":"-5.9879350662231445",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"553",
                     "descripcion":"San Luis (Plaza Pumarejo)",
                     "proximidad":"306.6300048828125",
                     "posicion":{
                        "latitud":"37.4007453918457",
                        "longitud":"-5.98879337310791",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"234",
                     "descripcion":"Amor de Dios (Plaza Europa)",
                     "proximidad":"329.3500061035156",
                     "posicion":{
                        "latitud":"37.39683532714844",
                        "longitud":"-5.993584156036377",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"14",
                              "label":"14",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"121",
                              "label":"C5",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"562",
                     "descripcion":"Alameda de Hércules (Trajano)",
                     "proximidad":"400.2900085449219",
                     "posicion":{
                        "latitud":"37.396766662597656",
                        "longitud":"-5.994439601898193",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"14",
                              "label":"14",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"761",
                     "descripcion":"Plaza San Román (Peñuelas)",
                     "proximidad":"484.29998779296875",
                     "posicion":{
                        "latitud":"37.39490509033203",
                        "longitud":"-5.986840724945068",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"1001",
                     "descripcion":"Jesus del Gran Poder (Sta. Barbara)",
                     "proximidad":"484.7099914550781",
                     "posicion":{
                        "latitud":"37.3966178894043",
                        "longitud":"-5.9953999519348145",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"359",
                     "descripcion":"San Luis (Arco Macarena)",
                     "proximidad":"484.80999755859375",
                     "posicion":{
                        "latitud":"37.402549743652344",
                        "longitud":"-5.989275932312012",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"8",
                     "descripcion":"Calatrava (Alameda de Hércules)",
                     "proximidad":"488.9800109863281",
                     "posicion":{
                        "latitud":"37.40150833129883",
                        "longitud":"-5.9940667152404785",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"14",
                              "label":"14",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"943",
                     "descripcion":"Dña. María Coronel (San Felipe)",
                     "proximidad":"497.239990234375",
                     "posicion":{
                        "latitud":"37.39384078979492",
                        "longitud":"-5.98954439163208",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"468",
                     "descripcion":"Feria (Bécquer)",
                     "proximidad":"501.8900146484375",
                     "posicion":{
                        "latitud":"37.40263748168945",
                        "longitud":"-5.991754531860352",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"237",
                     "descripcion":"Feria (Resolana)",
                     "proximidad":"540.989990234375",
                     "posicion":{
                        "latitud":"37.40298843383789",
                        "longitud":"-5.991813659667969",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"14",
                              "label":"14",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"25",
                     "descripcion":"Muñoz León (Sánchez Perrier)",
                     "proximidad":"550.8900146484375",
                     "posicion":{
                        "latitud":"37.401397705078125",
                        "longitud":"-5.985486030578613",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"82",
                              "label":"C2",
                              "color":"#008431"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"246",
                     "descripcion":"Muñoz León (Puerta de Córdoba)",
                     "proximidad":"556.0999755859375",
                     "posicion":{
                        "latitud":"37.402549743652344",
                        "longitud":"-5.98706579208374",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"10",
                           "label":"10",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"19",
                     "descripcion":"Parlamento de Andalucía (Macarena)",
                     "proximidad":"557.6099853515625",
                     "posicion":{
                        "latitud":"37.40306854248047",
                        "longitud":"-5.988490104675293",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"81",
                              "label":"C1",
                              "color":"#008431"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"26",
                     "descripcion":"Parlamento de Andalucía (Macarena)",
                     "proximidad":"571.6699829101562",
                     "posicion":{
                        "latitud":"37.40321350097656",
                        "longitud":"-5.988546371459961",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"82",
                           "label":"C2",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"925",
                     "descripcion":"Parlamento de Andalucía (Macarena)",
                     "proximidad":"577.3800048828125",
                     "posicion":{
                        "latitud":"37.40326690673828",
                        "longitud":"-5.988546371459961",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"28",
                     "descripcion":"Parlamento de Andalucía (Macarena)",
                     "proximidad":"585.1500244140625",
                     "posicion":{
                        "latitud":"37.40326690673828",
                        "longitud":"-5.988245964050293",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"2",
                           "label":"02",
                           "color":"#f54129"
                        }
                     }
                  },
                  {
                     "codigo":"249",
                     "descripcion":"Don Fadrique (Macarena)",
                     "proximidad":"589.1300048828125",
                     "posicion":{
                        "latitud":"37.40351104736328",
                        "longitud":"-5.989348411560059",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"14",
                           "label":"14",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"18",
                     "descripcion":"Resolana (Feria)",
                     "proximidad":"589.3099975585938",
                     "posicion":{
                        "latitud":"37.403350830078125",
                        "longitud":"-5.992218494415283",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"2",
                              "label":"02",
                              "color":"#f54129"
                           },
                           {
                              "macro":"81",
                              "label":"C1",
                              "color":"#008431"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"577",
                     "descripcion":"Plaza Ponce de León",
                     "proximidad":"593.530029296875",
                     "posicion":{
                        "latitud":"37.39339065551758",
                        "longitud":"-5.9875969886779785",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"24",
                           "label":"24",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"20",
                     "descripcion":"Ronda de Capuchinos (San Julián)",
                     "proximidad":"596.0599975585938",
                     "posicion":{
                        "latitud":"37.39972686767578",
                        "longitud":"-5.983828544616699",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"81",
                              "label":"C1",
                              "color":"#008431"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"921",
                     "descripcion":"Plaza Ponce de León",
                     "proximidad":"601.0",
                     "posicion":{
                        "latitud":"37.39329528808594",
                        "longitud":"-5.987661361694336",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"20",
                           "label":"20",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"963",
                     "descripcion":"Plaza Ponce de León",
                     "proximidad":"606.5900268554688",
                     "posicion":{
                        "latitud":"37.39329147338867",
                        "longitud":"-5.987514019012451",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"10",
                           "label":"10",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"576",
                     "descripcion":"Plaza Ponce de Léon",
                     "proximidad":"612.25",
                     "posicion":{
                        "latitud":"37.39321517944336",
                        "longitud":"-5.987573146820068",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"11",
                           "label":"11",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"24",
                     "descripcion":"Ronda de Capuchinos (León XIII)",
                     "proximidad":"614.27001953125",
                     "posicion":{
                        "latitud":"37.3996696472168",
                        "longitud":"-5.983595371246338",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"82",
                              "label":"C2",
                              "color":"#008431"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"920",
                     "descripcion":"Plaza Ponce de León",
                     "proximidad":"616.5700073242188",
                     "posicion":{
                        "latitud":"37.393218994140625",
                        "longitud":"-5.987441539764404",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"12",
                           "label":"12",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"247",
                     "descripcion":"Ponce de León",
                     "proximidad":"622.1199951171875",
                     "posicion":{
                        "latitud":"37.39307403564453",
                        "longitud":"-5.9877095222473145",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"27",
                              "label":"27",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"32",
                              "label":"32",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"41",
                     "descripcion":"Imagen (Plaza Encarnación)",
                     "proximidad":"625.0999755859375",
                     "posicion":{
                        "latitud":"37.39269256591797",
                        "longitud":"-5.991211414337158",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"27",
                              "label":"27",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"32",
                              "label":"32",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"166",
                     "descripcion":"Almirante Apodaca (Ponce de León)",
                     "proximidad":"625.3099975585938",
                     "posicion":{
                        "latitud":"37.392982482910156",
                        "longitud":"-5.987910747528076",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"9",
                     "descripcion":"Plaza Ponce de León",
                     "proximidad":"629.1500244140625",
                     "posicion":{
                        "latitud":"37.393035888671875",
                        "longitud":"-5.987616062164307",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"32",
                           "label":"32",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"248",
                     "descripcion":"Plaza Ponce de Leon (Juan de Mesa)",
                     "proximidad":"631.760009765625",
                     "posicion":{
                        "latitud":"37.393089294433594",
                        "longitud":"-5.987385272979736",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"27",
                           "label":"27",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"238",
                     "descripcion":"San Juan de Ribera (Macarena)",
                     "proximidad":"647.2100219726562",
                     "posicion":{
                        "latitud":"37.40354919433594",
                        "longitud":"-5.987237453460693",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"2",
                              "label":"02",
                              "color":"#f54129"
                           },
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"70",
                     "descripcion":"Laraña (Plaza Encarnación)",
                     "proximidad":"654.9000244140625",
                     "posicion":{
                        "latitud":"37.39275360107422",
                        "longitud":"-5.992920398712158",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"27",
                              "label":"27",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"32",
                              "label":"32",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"672",
                     "descripcion":"Jerónimo de Córdoba (Supermercado)",
                     "proximidad":"658.030029296875",
                     "posicion":{
                        "latitud":"37.39311218261719",
                        "longitud":"-5.986669540405273",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"16",
                           "label":"16",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"720",
                     "descripcion":"Plaza P. Jerónimo de Córdoba",
                     "proximidad":"669.27001953125",
                     "posicion":{
                        "latitud":"37.39303970336914",
                        "longitud":"-5.986572265625",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"15",
                           "label":"15",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"27",
                     "descripcion":"Resolana (Barqueta)",
                     "proximidad":"683.0999755859375",
                     "posicion":{
                        "latitud":"37.4036750793457",
                        "longitud":"-5.993996620178223",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"818",
                     "descripcion":"Resolana (Barqueta)",
                     "proximidad":"683.9299926757812",
                     "posicion":{
                        "latitud":"37.403778076171875",
                        "longitud":"-5.993766784667969",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"82",
                           "label":"C2",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"930",
                     "descripcion":"Resolana (Barqueta)",
                     "proximidad":"702.719970703125",
                     "posicion":{
                        "latitud":"37.40382385253906",
                        "longitud":"-5.994117259979248",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"2",
                           "label":"02",
                           "color":"#f54129"
                        }
                     }
                  },
                  {
                     "codigo":"461",
                     "descripcion":"María Auxiliadora (Puerta Osario)",
                     "proximidad":"711.9400024414062",
                     "posicion":{
                        "latitud":"37.39525604248047",
                        "longitud":"-5.983211517333984",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"11",
                              "label":"11",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"12",
                              "label":"12",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"16",
                              "label":"16",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"479",
                     "descripcion":"María Auxiliadora (Jardines del Valle)",
                     "proximidad":"720.3300170898438",
                     "posicion":{
                        "latitud":"37.39558410644531",
                        "longitud":"-5.982901573181152",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"15",
                              "label":"15",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"22",
                     "descripcion":"María Auxiliadora (Puerta Osario)",
                     "proximidad":"727.6400146484375",
                     "posicion":{
                        "latitud":"37.394493103027344",
                        "longitud":"-5.983595371246338",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"785",
                     "descripcion":"María Auxiliadora (Puerta Osario)",
                     "proximidad":"731.6099853515625",
                     "posicion":{
                        "latitud":"37.3941535949707",
                        "longitud":"-5.983860969543457",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"470",
                     "descripcion":"María Auxiliadora (Puerta Osario)",
                     "proximidad":"732.2899780273438",
                     "posicion":{
                        "latitud":"37.395042419433594",
                        "longitud":"-5.983096122741699",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"11",
                              "label":"11",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"12",
                              "label":"12",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"32",
                     "descripcion":"Teniente Borges (Plaza Duque)",
                     "proximidad":"733.0599975585938",
                     "posicion":{
                        "latitud":"37.3936653137207",
                        "longitud":"-5.996261119842529",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"808",
                     "descripcion":"Torneo (Barqueta)",
                     "proximidad":"734.4099731445312",
                     "posicion":{
                        "latitud":"37.40359878540039",
                        "longitud":"-5.995233535766602",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"83",
                           "label":"C3",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"50",
                     "descripcion":"Avenida La Cruz Roja (Clínica)",
                     "proximidad":"737.489990234375",
                     "posicion":{
                        "latitud":"37.4006462097168",
                        "longitud":"-5.982527732849121",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"11",
                              "label":"11",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"12",
                              "label":"12",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"16",
                              "label":"16",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"809",
                     "descripcion":"Torneo (Barqueta)",
                     "proximidad":"739.0399780273438",
                     "posicion":{
                        "latitud":"37.40359115600586",
                        "longitud":"-5.995334625244141",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"81",
                           "label":"C1",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"960",
                     "descripcion":"Plaza del Duque",
                     "proximidad":"742.280029296875",
                     "posicion":{
                        "latitud":"37.39314270019531",
                        "longitud":"-5.995703220367432",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"13",
                           "label":"13",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"16",
                     "descripcion":"Torneo (Puerta de San Juan)",
                     "proximidad":"742.6099853515625",
                     "posicion":{
                        "latitud":"37.40080261230469",
                        "longitud":"-5.998100757598877",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"3",
                              "label":"03",
                              "color":"#f54129"
                           },
                           {
                              "macro":"6",
                              "label":"06",
                              "color":"#f54129"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"7",
                     "descripcion":"Plaza del Duque (La Campana)",
                     "proximidad":"745.760009765625",
                     "posicion":{
                        "latitud":"37.392723083496094",
                        "longitud":"-5.995068073272705",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"32",
                           "label":"32",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"656",
                     "descripcion":"María Auxiliadora (Laborat. Municipal)",
                     "proximidad":"746.3699951171875",
                     "posicion":{
                        "latitud":"37.39520263671875",
                        "longitud":"-5.98280668258667",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"16",
                              "label":"16",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"282",
                     "descripcion":"María Auxiliadora (Dr. Relimpio)",
                     "proximidad":"747.7100219726562",
                     "posicion":{
                        "latitud":"37.39549255371094",
                        "longitud":"-5.982613563537598",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"15",
                           "label":"15",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"1",
                     "descripcion":"Campana (Sierpes)",
                     "proximidad":"750.0399780273438",
                     "posicion":{
                        "latitud":"37.3927116394043",
                        "longitud":"-5.995132923126221",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"27",
                           "label":"27",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"23",
                     "descripcion":"Ronda de Capuchinos (Avenida Miraflores)",
                     "proximidad":"753.2100219726562",
                     "posicion":{
                        "latitud":"37.398807525634766",
                        "longitud":"-5.981822490692139",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"82",
                              "label":"C2",
                              "color":"#008431"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"810",
                     "descripcion":"Torneo (Barqueta)",
                     "proximidad":"760.5599975585938",
                     "posicion":{
                        "latitud":"37.403018951416016",
                        "longitud":"-5.996518135070801",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"84",
                           "label":"C4",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"563",
                     "descripcion":"Plaza del Duque",
                     "proximidad":"762.219970703125",
                     "posicion":{
                        "latitud":"37.39291763305664",
                        "longitud":"-5.995713233947754",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"14",
                           "label":"14",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"608",
                     "descripcion":"José Laguillo (Puerta Osario)",
                     "proximidad":"775.2999877929688",
                     "posicion":{
                        "latitud":"37.39386749267578",
                        "longitud":"-5.983516216278076",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"20",
                           "label":"20",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"786",
                     "descripcion":"Ronda de Capuchinos (La Trinidad)",
                     "proximidad":"777.489990234375",
                     "posicion":{
                        "latitud":"37.397865295410156",
                        "longitud":"-5.9815354347229",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"29",
                     "descripcion":"Torneo (Puerta de San Juan)",
                     "proximidad":"781.6400146484375",
                     "posicion":{
                        "latitud":"37.400848388671875",
                        "longitud":"-5.99855375289917",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"3",
                              "label":"03",
                              "color":"#f54129"
                           },
                           {
                              "macro":"6",
                              "label":"06",
                              "color":"#f54129"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"21",
                     "descripcion":"Ronda de Capuchinos (La Trinidad)",
                     "proximidad":"781.8200073242188",
                     "posicion":{
                        "latitud":"37.39767837524414",
                        "longitud":"-5.981503009796143",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"11",
                              "label":"11",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"12",
                              "label":"12",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"16",
                              "label":"16",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"81",
                              "label":"C1",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"832",
                     "descripcion":"Concejal Jiménez Becerril (Barqueta)",
                     "proximidad":"797.3900146484375",
                     "posicion":{
                        "latitud":"37.40446472167969",
                        "longitud":"-5.994868755340576",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"3",
                              "label":"03",
                              "color":"#f54129"
                           },
                           {
                              "macro":"6",
                              "label":"06",
                              "color":"#f54129"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"71",
                     "descripcion":"Avenida Miraflores (San Juan Bosco)",
                     "proximidad":"804.77001953125",
                     "posicion":{
                        "latitud":"37.39889144897461",
                        "longitud":"-5.981245517730713",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"11",
                              "label":"11",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"12",
                              "label":"12",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"16",
                              "label":"16",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"480",
                     "descripcion":"José Laguillo (Puerta Osario)",
                     "proximidad":"813.7000122070312",
                     "posicion":{
                        "latitud":"37.393898010253906",
                        "longitud":"-5.982935428619385",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"82",
                           "label":"C2",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"834",
                     "descripcion":"Concejal Jiménez Becerril (Barqueta)",
                     "proximidad":"816.8599853515625",
                     "posicion":{
                        "latitud":"37.404476165771484",
                        "longitud":"-5.995269298553467",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"3",
                              "label":"03",
                              "color":"#f54129"
                           },
                           {
                              "macro":"6",
                              "label":"06",
                              "color":"#f54129"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"784",
                     "descripcion":"José Laguillo (Puerta Osario)",
                     "proximidad":"818.8300170898438",
                     "posicion":{
                        "latitud":"37.393798828125",
                        "longitud":"-5.982956886291504",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"32",
                              "label":"32",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"81",
                              "label":"C1",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"337",
                     "descripcion":"Santa Vicenta María (Teniente Borges)",
                     "proximidad":"819.5",
                     "posicion":{
                        "latitud":"37.393585205078125",
                        "longitud":"-5.997483730316162",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"300",
                     "descripcion":"Carretera Carmona (Ronda de Capuchinos)",
                     "proximidad":"835.6099853515625",
                     "posicion":{
                        "latitud":"37.3978385925293",
                        "longitud":"-5.9808783531188965",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"15",
                           "label":"15",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"334",
                     "descripcion":"Recaredo (Puerta Osario)",
                     "proximidad":"845.2000122070312",
                     "posicion":{
                        "latitud":"37.3924560546875",
                        "longitud":"-5.984158515930176",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"24",
                              "label":"24",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"27",
                              "label":"27",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"288",
                     "descripcion":"Carretera Carmona (Ronda de Capuchinos)",
                     "proximidad":"848.2000122070312",
                     "posicion":{
                        "latitud":"37.397762298583984",
                        "longitud":"-5.980741500854492",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"15",
                           "label":"15",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"281",
                     "descripcion":"Gonzalo Bilbao (Puerta Osario)",
                     "proximidad":"848.77001953125",
                     "posicion":{
                        "latitud":"37.39300537109375",
                        "longitud":"-5.983364582061768",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"24",
                              "label":"24",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"27",
                              "label":"27",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"32",
                              "label":"32",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"280",
                     "descripcion":"Arroyo (José Laguillo)",
                     "proximidad":"864.3800048828125",
                     "posicion":{
                        "latitud":"37.39384078979492",
                        "longitud":"-5.982280731201172",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"20",
                           "label":"20",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"366",
                     "descripcion":"El Silencio",
                     "proximidad":"867.2100219726562",
                     "posicion":{
                        "latitud":"37.39249801635742",
                        "longitud":"-5.99692440032959",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"112",
                     "descripcion":"San Juan de Ribera (Policlínico)",
                     "proximidad":"867.6099853515625",
                     "posicion":{
                        "latitud":"37.40553283691406",
                        "longitud":"-5.986733436584473",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"2",
                              "label":"02",
                              "color":"#f54129"
                           },
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"239",
                     "descripcion":"San Juan de Ribera (Policlínico)",
                     "proximidad":"871.3200073242188",
                     "posicion":{
                        "latitud":"37.40542984008789",
                        "longitud":"-5.98631477355957",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"2",
                              "label":"02",
                              "color":"#f54129"
                           },
                           {
                              "macro":"10",
                              "label":"10",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"13",
                              "label":"13",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"283",
                     "descripcion":"Arroyo (Urquiza)",
                     "proximidad":"880.4500122070312",
                     "posicion":{
                        "latitud":"37.39458084106445",
                        "longitud":"-5.981503009796143",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"20",
                           "label":"20",
                           "color":"#000d6f"
                        }
                     }
                  },
                  {
                     "codigo":"108",
                     "descripcion":"Jesús de Las Tres Caídas (Alfalfa)",
                     "proximidad":"886.6300048828125",
                     "posicion":{
                        "latitud":"37.39033508300781",
                        "longitud":"-5.99131441116333",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"780",
                     "descripcion":"Torneo (San Lorenzo)",
                     "proximidad":"910.4000244140625",
                     "posicion":{
                        "latitud":"37.398006439208984",
                        "longitud":"-6.000622749328613",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"3",
                              "label":"03",
                              "color":"#f54129"
                           },
                           {
                              "macro":"6",
                              "label":"06",
                              "color":"#f54129"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"31",
                     "descripcion":"Santiago (Pza J. de La Redención)",
                     "proximidad":"914.3699951171875",
                     "posicion":{
                        "latitud":"37.390872955322266",
                        "longitud":"-5.985799789428711",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"888",
                     "descripcion":"Recaredo (San Roque)",
                     "proximidad":"926.8599853515625",
                     "posicion":{
                        "latitud":"37.391544342041016",
                        "longitud":"-5.984123706817627",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"49",
                     "descripcion":"Avenida La Cruz Roja (Antonio Machín)",
                     "proximidad":"940.3200073242188",
                     "posicion":{
                        "latitud":"37.40287399291992",
                        "longitud":"-5.981393337249756",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"11",
                              "label":"11",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"12",
                              "label":"12",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"16",
                              "label":"16",
                              "color":"#000d6f"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"889",
                     "descripcion":"Recaredo (San Roque)",
                     "proximidad":"947.7100219726562",
                     "posicion":{
                        "latitud":"37.39125061035156",
                        "longitud":"-5.984236717224121",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"1",
                              "label":"01",
                              "color":"#f54129"
                           },
                           {
                              "macro":"24",
                              "label":"24",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"27",
                              "label":"27",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"83",
                              "label":"C3",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"94",
                     "descripcion":"Villegas (Pza. El Salvador)",
                     "proximidad":"966.969970703125",
                     "posicion":{
                        "latitud":"37.389835357666016",
                        "longitud":"-5.992988109588623",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"106",
                     "descripcion":"Águilas (Casa Pilatos)",
                     "proximidad":"975.97998046875",
                     "posicion":{
                        "latitud":"37.38988494873047",
                        "longitud":"-5.98705530166626",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"555",
                     "descripcion":"Plaza de La Magdalena",
                     "proximidad":"983.3200073242188",
                     "posicion":{
                        "latitud":"37.39113998413086",
                        "longitud":"-5.9969072341918945",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"40",
                              "label":"40",
                              "color":"#000d6f"
                           },
                           {
                              "macro":"121",
                              "label":"C5",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"781",
                     "descripcion":"Torneo (San Lorenzo)",
                     "proximidad":"984.9500122070312",
                     "posicion":{
                        "latitud":"37.398067474365234",
                        "longitud":"-6.001469135284424",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":[
                           {
                              "macro":"3",
                              "label":"03",
                              "color":"#f54129"
                           },
                           {
                              "macro":"6",
                              "label":"06",
                              "color":"#f54129"
                           },
                           {
                              "macro":"84",
                              "label":"C4",
                              "color":"#008431"
                           }
                        ]
                     }
                  },
                  {
                     "codigo":"332",
                     "descripcion":"Monsalves (Fernán Caballero)",
                     "proximidad":"987.6699829101562",
                     "posicion":{
                        "latitud":"37.39226150512695",
                        "longitud":"-5.998556613922119",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"121",
                           "label":"C5",
                           "color":"#008431"
                        }
                     }
                  },
                  {
                     "codigo":"630",
                     "descripcion":"Plaza Magdalena",
                     "proximidad":"989.9299926757812",
                     "posicion":{
                        "latitud":"37.39119338989258",
                        "longitud":"-5.997121810913086",
                        "altura":"20.0"
                     },
                     "lineasCoincidentes":{
                        "linea":{
                           "macro":"43",
                           "label":"43",
                           "color":"#000d6f"
                        }
                     }
                  }
               ]
            },
            "_xmlns:ns2":"http://services.infotusws.tussam.com/",
            "__prefix":"ns2"
         },
         "__prefix":"soap"
      },
      "_xmlns:soap":"http://schemas.xmlsoap.org/soap/envelope/",
      "__prefix":"soap"
   }
}

    */

    /*
    var dictionary = {
      'LATITUDE' : pos.coords.latitude,
      'LONGITUDE': pos.coords.longitude
    };
    Pebble.sendAppMessage(dictionary,
    function(e) {
      console.log('You are latitude -> ' + dictionary.LATITUDE + " longitude ->" + dictionary.LONGITUDE);
    },
    function(e) {
      console.log('Error sending info to Pebble!');
    }); */
  }

  function error(err) {
    //Si no funciona la geolocalización devolvemos el centro de sevilla
    console.log("Position not found. Using default position");
    var pos = {
      coords : {
        latitude: 37.3881,
        longitude: -5.9823
      }
    };

    var dictionary = {
      'LATITUDE' : pos.coords.latitude,
      'LONGITUDE': pos.coords.longitude
    };

    Pebble.sendAppMessage(dictionary,
    function(e) {
      console.log('You are latitude -> ' + dictionary.LATITUDE + " longitude ->" + dictionary.LONGITUDE);
    },
    function(e) {
      console.log('Error sending info to Pebble!');
    });
  }

  var options = {
    enableHighAccuracy: true,
    maximumAge: 10000,
    timeout: 10000
  };

  navigator.geolocation.getCurrentPosition(success, error, options);
}

module.exports = {
  getNodosCercanos : getNodosCercanos
};
